### ISSUE TITLE
Story text invisible in Chrome

### ISSUE THREAD

**Issue by juhana** [juhana/starborn#1]
See https://github.com/juhana/vorple/issues/4

**Comment by cibersheep** [comment]
Hello. It seems that the problem is back.
I have tried Firefox 49.0.2 and Chrome (both in Ubuntu) and text seems to go behind the image.

**Comment by vvs-** [comment]
Firefox 48 on Windows and Firefox 68 on Linux - the same problem, but the text is still visible in Internet Explorer 8. Is there any workaround?

After renaming `main-bg.jpg` the text is now visible but hyperlinks still are not clickable, though menu on the right works.

**Comment by juhana** [comment]
The CSS would need to be rewritten for modern browsers. I'll make a note to fix it when there's a good spot for it.

**Comment by juhana** [comment]
The CSS is now updated so that it's at least playable.
